### ISSUE TITLE
Doesn't support <inheritdoc/>

### ISSUE THREAD

**Issue by point32** [AonaSuzutsuki/KmCsharpHtmlDocGenerator#2]
.NET Sdk: 8.0.200
I created a new C# Library
'''shell
dotnet new classlib -o ApiDocTest
'''
And then I added these two files:

Parent.cs
```CSharp
namespace ApiDocTest;

/// <summary>
/// Document for ApiDocTest.Parent
/// </summary>
public class Parent
{
    /// <summary>
    /// Document for Method 'Function'
    /// </summary>
    /// <returns></returns>
    public virtual string Function()
    {
        return "Function in ApiDocTest.Parent";
    }
}
```

Child.cs
```CSharp
namespace ApiDocTest;

public class Child : Parent
{
    public override string Function()
    {
        return "Function in ApiDocTest.Child";
    }
}
```

Next, I built the project and run the following command:
```shell
HtmlGenerator.exe bin\Debug\net8.0\ApiDocTest.xml
```

This is the output:
```
Start XmlParse D:\Notran\ApiDocTest\ApiDocTest\bin\Debug\net8.0\ApiDocTest.xml
  50% Xml First Parse   T:ApiDocTest.Parent
 100% Xml First Parse   M:ApiDocTest.Parent.Function
Completed Xml First Parse.

  50% Xml Second Parse  T:ApiDocTest.Parent
 100% Xml Second Parse  M:ApiDocTest.Parent.Function
Completed Xml Second Parse.

Start C# code analysis.
not found "System.Collections.Immutable" assembly.
not found "System.Composition.AttributedModel" assembly.
not found "System.Composition.Convention" assembly.
not found "System.Composition.Runtime" assembly.
not found "System.Composition.Hosting" assembly.
not found "System.Composition.TypedParts" assembly.
not found "System.Reflection.Metadata" assembly.
not found "System.Text.Encoding.CodePages" assembly.
not found "System.Threading.Tasks.Extensions" assembly.
not found "Microsoft.CodeAnalysis" assembly.
not found "Microsoft.CodeAnalysis.CSharp" assembly.
not found "Microsoft.CodeAnalysis.VisualBasic" assembly.
not found "Microsoft.CodeAnalysis.Workspaces" assembly.
not found "Microsoft.CodeAnalysis.CSharp.Workspaces" assembly.
not found "Microsoft.CodeAnalysis.VisualBasic.Workspaces" assembly.
not found "System.Buffers" assembly.
not found "System.Numerics.Vectors" assembly.
not found "System.Runtime.CompilerServices.Unsafe" assembly.
not found "System.Memory" assembly.
not found "System.Buffers" assembly.
not found "System.Collections.Immutable" assembly.
not found "System.Composition.AttributedModel" assembly.
not found "System.Composition.Convention" assembly.
not found "System.Composition.Runtime" assembly.
not found "System.Composition.Hosting" assembly.
not found "System.Composition.TypedParts" assembly.
not found "System.Numerics.Vectors" assembly.
not found "System.Reflection.Metadata" assembly.
not found "System.Runtime.CompilerServices.Unsafe" assembly.
not found "System.Memory" assembly.
not found "System.Text.Encoding.CodePages" assembly.
not found "System.Threading.Tasks.Extensions" assembly.
not found "Microsoft.CodeAnalysis" assembly.
not found "Microsoft.CodeAnalysis.CSharp" assembly.
not found "Microsoft.CodeAnalysis.VisualBasic" assembly.
not found "Microsoft.CodeAnalysis.Workspaces" assembly.
not found "Microsoft.CodeAnalysis.CSharp.Workspaces" assembly.
not found "Microsoft.CodeAnalysis.VisualBasic.Workspaces" assembly.
   1% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\ArrayExtension.cs
   3% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\DictionaryExtension.cs
   5% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentExtensions\Properties\AssemblyInfo.cs
   7% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\StringExtension.cs
   9% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CommonPath\PathUtils.cs
  11% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\CsXmlDocumentParser.cs
  13% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\Element.cs
  15% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\ElementType.cs
  17% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\IElementOfInheritance.cs
  19% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\Member.cs
  21% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\MethodType.cs
  23% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\NamespaceItem.cs
  25% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\CSharpEasyAnalyzer.cs
  26% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\IAccessorInfo.cs
  28% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\MethodParameter\MethodParameterConverter.cs
  30% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\Properties\AssemblyInfo.cs
  32% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\Reader.cs
  34% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\ClassType.cs
  36% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\ClassInfo.cs
  38% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\Constants.cs
  40% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\CSharpDocumentGenerator.cs
  42% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\Writer.cs
  44% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\AttributeInfo.cs
  46% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentToHtml\Properties\AssemblyInfo.cs
  48% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentToHtml\Template\TemplateLoader.cs
  50% Code Analysis     src\CsXmlDocumentToHtml\XmlDocumentToHtml\Writer\CsXmlToHtmlWriter.cs
  51% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\ArrayExtension.cs
  53% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\DictionaryExtension.cs
  55% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentExtensions\Properties\AssemblyInfo.cs
  57% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentExtensions\Extensions\StringExtension.cs
  59% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CommonPath\PathUtils.cs
  61% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\CsXmlDocumentParser.cs
  63% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\Element.cs
  65% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\ElementType.cs
  67% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\IElementOfInheritance.cs
  69% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\Member.cs
  71% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\MethodType.cs
  73% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\CsXmlDocument\NamespaceItem.cs
  75% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\CSharpEasyAnalyzer.cs
  76% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\IAccessorInfo.cs
  78% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\MethodParameter\MethodParameterConverter.cs
  80% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\Properties\AssemblyInfo.cs
  82% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\Reader.cs
  84% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\ClassType.cs
  86% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\ClassInfo.cs
  88% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\Constants.cs
  90% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\EasyCs\CSharpDocumentGenerator.cs
  92% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\Writer.cs
  94% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentParser\XmlWrapper\AttributeInfo.cs
  96% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentToHtml\Properties\AssemblyInfo.cs
  98% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentToHtml\Template\TemplateLoader.cs
 100% Syntactic Analysis        src\CsXmlDocumentToHtml\XmlDocumentToHtml\Writer\CsXmlToHtmlWriter.cs
Completed C# code analysis.
```

It works well, but when I added `<inheritdoc/>` to Child.cs, it failed
```CSharp
namespace ApiDocTest;

/// <inheritdoc cref="ApiDocTest.Parent"/>
public class Child : Parent
{
    ///<inheritdoc/>
    public override string Function()
    {
        return "Function in ApiDocTest.Child";
    }
}
```

```shell
HtmlGenerator.exe bin\Debug\net8.0\ApiDocTest.xml
```

Console output:
```
Start XmlParse D:\Notran\ApiDocTest\ApiDocTest\bin\Debug\net8.0\ApiDocTest.xml
  33% Xml First Parse   T:ApiDocTest.Parent
  66% Xml First Parse   M:ApiDocTest.Parent.Function

Unhandled exception:  System.NullReferenceException: Object reference not set to an instance of an object.
   at XmlDocumentExtensions.Extensions.StringExtension.UnifiedNewLine(String text)
   at XmlDocumentParser.CsXmlDocument.CsXmlDocumentParser.RemoveFirstLastBreakLine(String text)
   at XmlDocumentParser.CsXmlDocument.CsXmlDocumentParser.FirstParse(Reader reader)
   at XmlDocumentParser.CsXmlDocument.CsXmlDocumentParser.FirstParse(String xmlPath)
   at XmlDocumentParser.CsXmlDocument.CsXmlDocumentParser.Parse()
   at XmlDocumentParser.CsXmlDocument.CsXmlDocumentParser.ParseMultiFiles(String[] files, String rootName, XmlDocumentParseProgressEventHandler parseProgressEventHandler, XmlDocumentParseCompletedEventHandler completed, Action`1 startAct)
   at XMLDocumentToHtmlCUI.Program.Main(String[] args)
```

Both `<inheritdoc>` and `<inheritdoc cref="ApiDocTest.Parent"/>` will raise this exception.

**Comment by AonaSuzutsuki** [comment]
Thanks for the report.
I am currently out of development so I don't think I will be able to respond it right away.
I will take a look when I have more time.
